---
name: CI
# yamllint disable-line rule:truthy
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure variables
        id: variables
        run: |
          BUILD=$(date '+%Y%m%d%H%M%S')
          echo "::set-output name=build::${BUILD}"

      - name: Build
        run: sudo ./build.sh

      - name: print sha256sum
        run: cat output/sha256

      - name: Upload iso artifact
        uses: actions/upload-artifact@v2
        with:
          name: mbp-ubuntu-${{ steps.variables.outputs.build }}
          path: ${{ github.workspace }}/output/*

      - name: Instructions for putting it back together
        run: |
          cat << EOF
          Download all the artifacts, and put them in a folder
          without other files. Then run:"
          unzip "*.z??.zip"
          cat livecd-${{ steps.variables.outputs.build }}-mbp.z?? > cd.zip
          echo unzip cd.zip
          EOF

      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/output/*
          tag_name: v20.04-${{ steps.variables.outputs.build }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
