---
name: CI
# yamllint disable-line rule:truthy
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure variables
        id: variables
        run: |
          sudo apt install curl
          VERSION=5.10
          ALTERNATIVE=mbp
          LATEST_BUILD=$(curl -s https://mbp-ubuntu-kernel.herokuapp.com/ -L |
                         grep "linux-image-5.10" | grep ${ALTERNATIVE} |
                         grep a | cut -d'>' -f2 | cut -d'<' -f1 |sort -r | head -n 1 | cut -d'_' -f1 |
                         cut -d'-' -f 3-20)
          echo "Using kernel ${LATEST_BUILD}"
          echo "::set-output name=version::${LATEST_BUILD}"

      - name: Build
        run: KERNEL_VERSION=${{ steps.variables.outputs.version }} sudo ./build.sh

      - name: print sha256sum
        run: cat output/sha256

      - name: Upload iso artifact
        uses: actions/upload-artifact@v2
        with:
          name: mbp-ubuntu-${{ steps.variables.outputs.version }}
          path: ${{ github.workspace }}/output/*

      - name: Instructions for putting it back together
        run: |
          cat << EOF
          Download all the artifacts, and put them in a folder
          without other files. Then run:"
          unzip "*.z??.zip"
          cat livecd-${{ steps.variables.outputs.version }}-mbp.z?? > cd.zip
          echo unzip cd.zip
          EOF

      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/output/*
          tag_name: v20.04-${{ steps.variables.outputs.version }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
